name: Upload Freelancy

on:
	push:
		branches:
			- main
jobs:
	deploy:
		runs-on: ubuntu-latest
		steps:
			-	name: Checkout Repository
				uses: actions/checkout@v4
				
			- name: Sync Files to 53
  			uses: jakejarvis/s3-sync-action@master
        with:
					args: --acl public-read --follow-symlinks --delete
			env:
				AWS_53_BUCKET: ${{ secrets. AWS_53_BUCKET }}
				AWS_ACCESS_KEY_ID: ${{ secrets. AWS_ACCESS_KEY_ID }}
				AWS_SECRET_ACCESS_KEY: ${{ secrets. AWS_SECRET_ACCESS_KEY }}
				AWS_REGION: ${{ secrets. AWS REGION }}
				SOURCE_DIR: "Freelancy" # Change if your files are in a different directory
